### ISSUE TITLE
An error occurred while creating the topic model

### ISSUE THREAD

**Issue by monajalal** [davidatbu/openFraming#285] opened 2020-07-13 21:14 UTC
<img width="1119" alt="Screen Shot 2020-07-13 at 5 12 02 PM" src="https://user-images.githubusercontent.com/1892917/87354225-3401fd80-c52c-11ea-8352-a6d79b19bc25.png">

*Leaving this here until we are sure what is the exact reason for error. (in future, the error perhaps should be more detailed)

**Comment by davidatbu** [comment] 2020-07-16 14:12
Duplicate of #279

**Closed by davidatbu** 2020-07-16 14:12 UTC
Labels: backend, bug, high-priority
